services:
  db:
    container_name: db
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo-data:/data/db
  factorialapi:
    container_name: factorialapi
    image: factorialapi
    ports:
      - 8080:8080
    depends_on:
      - db
  factorialfrontend:
    container_name: factorialfrontend
    image: factorialfrontend
    ports:
      - 8090:8090
    depends_on:
      - factorialapi
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    depends_on:
      - db
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: db
volumes:
  mongo-data:
    driver: local